on:
  push:
    paths:
      - 'springboot/**'

jobs:
  build-jvm:
    name: Build Springboot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Test
        if: success()
        run: mvn --projects springboot clean test
      - name: Build & Push Docker Image
        if: success()
        run: mvn --projects springboot  compile jib:build
        env:
          DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
          DOCKER_REGISTRY_PWD: ${{ secrets.DOCKER_REGISTRY_PWD }}


