on:
  push:
    paths:
      - 'quarkus/**'

jobs:
  build-jvm:
    name: Build Quarkus Native
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Test
        if: success()
        run: mvn clean test
      - name: Package
        if: success()
        run: mvn package -Pnative -Dquarkus.native.container-build=true
      - name: Build & Push Docker Image
        if: success()
        run: mvn package -Pnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.group=$DOCKER_REGISTRY_USER -Dquarkus.container-image.registry=registry.hub.docker.com  -Dquarkus.container-image.username=$DOCKER_REGISTRY_USER -Dquarkus.container-image.password=$DOCKER_REGISTRY_PWD
        env:
          DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
          DOCKER_REGISTRY_PWD: ${{ secrets.DOCKER_REGISTRY_PWD }}


